node:
  id: "id_01"
  cluster: "cluster_01"
static_resources:
  listeners:
  - name: web_mtls_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8001
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          idle_timeout: 1s
          codec_type: auto
          access_log:
          - name: envoy.file_access_log
            config:
              path: "/tmp/envoy-to-envoy-mtls.log"
          stat_prefix: ingress_http
          route_config:
            name: service_route
            virtual_hosts:
            - name: web_to_backend_mtls
              domains: ["*"]
              routes:
              - match:
                  prefix: "/hello"
                route:
                  cluster: web_server
              - match:
                  prefix: "/the/good/path"
                route:
                  cluster: web_server
              - match:
                  prefix: "/the/bad/path"
                route:
                  cluster: web_server
              - match:
                  prefix: "/good/backend"
                route:
                  cluster: web_to_backend_mtls
              - match:
                  prefix: "/good/db"
                route:
                  cluster: web_to_db_mtls
          http_filters:
          - name: envoy.ext_authz
            config:
              failure_mode_allow: false
              grpc_service:
                google_grpc:
                  target_uri: opa_web:9191
                  stat_prefix: ext_authz
                timeout: 0.5s
          - name: envoy.router

  clusters:
  - name: spire_agent
    connect_timeout: 0.25s
    http2_protocol_options: {}
    hosts:
      - pipe:
          path: /tmp/agent.sock
  - name: web_server
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: web_server
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8080
  - name: web_to_backend_mtls
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: ROUND_ROBIN
    hosts:
      - socket_address:
          address: backend
          port_value: 8001
    tls_context:
      common_tls_context:
        tls_certificate_sds_secret_configs:
          - name: "spiffe://domain.test/web-server"
            sds_config:
              api_config_source:
                api_type: GRPC
                grpc_services:
                  envoy_grpc:
                    cluster_name: spire_agent
        combined_validation_context:
          # validate the SPIFFE ID of the server
          default_validation_context:
            verify_subject_alt_name:
              - "spiffe://domain.test/backend-server"
          validation_context_sds_secret_config:
            name: "spiffe://domain.test"
            sds_config:
              api_config_source:
                api_type: GRPC
                grpc_services:
                  envoy_grpc:
                    cluster_name: spire_agent
        tls_params:
          ecdh_curves:
            - X25519:P-256:P-521:P-384
  - name: web_to_db_mtls
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: ROUND_ROBIN
    hosts:
      - socket_address:
          address: db
          port_value: 8001
    tls_context:
      common_tls_context:
        tls_certificate_sds_secret_configs:
          - name: "spiffe://domain.test/web-server"
            sds_config:
              api_config_source:
                api_type: GRPC
                grpc_services:
                  envoy_grpc:
                    cluster_name: spire_agent
        combined_validation_context:
          # validate the SPIFFE ID of the server
          default_validation_context:
            verify_subject_alt_name:
              - "spiffe://domain.test/db-server"
          validation_context_sds_secret_config:
            name: "spiffe://domain.test"
            sds_config:
              api_config_source:
                api_type: GRPC
                grpc_services:
                  envoy_grpc:
                    cluster_name: spire_agent
        tls_params:
          ecdh_curves:
            - X25519:P-256:P-521:P-384
